@startuml

[*] -> s_idle
s_idle -d-> s_release
s_idle -d-> s_releaseData : dirty
s_idle : 空闲状态，准备接受控制单元的请求

s_release -> s_idle : probe
s_release -d-> s_releaseAck
s_release : 释放缓存块所有权，无脏数据

s_releaseData -> s_idle : probe
s_releaseData -d-> s_releaseAck
s_releaseData : 写回脏数据

s_releaseAck -> s_idle
s_releaseAck : 等待从设备确认写回

@enduml
